### ISSUE TITLE
DiscreteUniform not an instance of DiscreteGen

### ISSUE THREAD

**Issue by schnecki** [haskell/statistics#152]
Hi,

I was wondering how one can draw samples from `DiscreteUniform` as there is no `DiscreteGen` instance defined.

Thanks in advance.

**Comment by schnecki** [comment]
bump

**Comment by Shimuuar** [comment]
I'm going to update both rmwc-random and statistics and I'll add instance to UniformDiscrete.

**Comment by dschrempf** [comment]
FYI, I just bumped into this...
