### ISSUE TITLE
`statistics-0.16.0.0` fails to build

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/statistics#180]
As seen [here](https://github.com/haskell/criterion/runs/4748526694?check_suite_focus=true#step:17:549):

```
[15 of 48] Compiling Statistics.Distribution.Gamma ( Statistics/Distribution/Gamma.hs, dist/build/Statistics/Distribution/Gamma.o, dist/build/Statistics/Distribution/Gamma.dyn_o )

Statistics/Distribution/Gamma.hs:141:25: error:
    • Variable not in scope: lп :: Double
    • Perhaps you meant ‘l’ (line 141)
    |
141 |     mean (GD a l) = a * lп
    |                         ^^
```

**Comment by Shimuuar** [comment]
Thank you for the report! Turns out making tarball from work tree is not all that great idea. I've uploaded 0.16.0.1 and blacklisted 0.16.0.0

Do you know any tool for making source distribution from clean git checkout? It would help with forgetting to push tags too

**Comment by RyanGlScott** [comment]
Thanks! And I'm afraid I don't know of a good way to automate uploading sdists from clean checkouts, other than being diligent about invoking `git status` beforehand to make sure everything is clean.

**Comment by Shimuuar** [comment]
Well being diligent isn't exactly my forte and it's a computer's job anyway. I cobbled together small script for that: https://github.com/Shimuuar/sdist-release
