### ISSUE TITLE
Possible overflow in Module      : Statistics.Correlation.Kendall

### ISSUE THREAD

**Issue by DayneSorvisto** [haskell/statistics#204]
Specifically, if n is large, then (fromIntegral n * (fromIntegral n-1)) might overflow an Int. 

Fix: convert n to Integer before performing the multiplication.

Can I create a PR?

**Comment by Shimuuar** [comment]
Are you referring to?

https://github.com/haskell/statistics/blob/f19804958c76e02e38457d4862fe6e69717736b2/Statistics/Correlation/Kendall.hs#L57-L69

I'm not sure that it's a real problem doing Integer arithmetic wouldn't hurt there. If you referring to

https://github.com/haskell/statistics/blob/f19804958c76e02e38457d4862fe6e69717736b2/Statistics/Correlation/Kendall.hs#L47-L49

It's Integer already
